### PR TITLE
fix(actix): support parsing arrays for schemas

### LINKED ISSUE #454: Arrays are not supported
With version 0.7.1:

i have a response struct like:

```rust
#[derive(Debug, Serialize, Clone, Apiv2Schema)]
struct TestResponse {
      // Some data
      position: [f32; 3],
}
```
With a fixed size array field called `position`. When I build my application I get the following errors:

```
error[E0425]: cannot find crate `raw_schema` in the list of imported crates
 --> my_crate/src/responses/test.rs
  |
6 | #[derive(Debug, Serialize, Clone, Apiv2Schema)]
  |                                   ^^^^^^^^^^^ not found in the list of imported crates
  |
  = note: this error originates in the derive macro `Apiv2Schema` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0425]: cannot find crate `required` in the list of imported crates
 --> my_crate/src/responses/test.rs
  |
6 | #[derive(Debug, Serialize, Clone, Apiv2Schema)]
  |                                   ^^^^^^^^^^^ not found in the list of imported crates
  |
  = note: this error originates in the derive macro `Apiv2Schema` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Removing the `position` field fixes compilation

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Array field types were not being parsed.
Also in this case errors were not being handled gracefully.

Resolves #454

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
@sireaev this should fix it.
@formlogic-kirk seems arrays were not being handled properly, would you mind taking a look at this fix?

File: macros/src/actix.rs [hunk 1]
```diff
@@ -1491,7 +1493,10 @@ fn handle_unnamed_field_struct(
                 continue;
             }
 
-            let ty_ref = get_field_type(field);
+            let ty_ref = match get_field_type(field) {
```
Comment (formlogic-kirk) [inline macros/src/actix.rs:1496]: good place for `let-else` if that's allowed by the msrv

**Review by formlogic-kirk — APPROVED** [review]
That looks good to me. I need to revisit the maps and see if this is happening for the value types there also

File: macros/src/actix.rs (hunk 1 above)
Comment (tiagolobocastro) [reply macros/src/actix.rs:1496]: hmm seems that it depends on the imported crates
With my lockfile it's 1.60 but if I delete it it's 1.65 due to:

┌─────────────────────────────────────────────────────────────────────
│ error: package `hashbrown v0.14.5` cannot be built because it requires rustc 1.63.0 or newer, while the currently active rustc version is 1.62.1                                                                                         │
│ error: package `serde_yaml v0.9.34+deprecated` cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.63.0                                                                               │
│ error: package `regex-automata v0.4.7` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.64.0                                                                                       │
└─────────────────────────────────────────────────────────────────────
```

Comment (formlogic-kirk) [reply macros/src/actix.rs:1496]: Fair enough. The MSRV aware resolver can't come soon enough
